
# 로깅 처리
logging:
  file:
    name: logs/authentication.log
    max-size: 500MB
    max-history: 10
  level:
    root: info
    '[com.mzc.authencation_server]': debug



# JPA - MySQL 설정
spring:
  datasource:
    #url: jdbc:mysql://db-server:3306/item_db
    url: jdbc:mysql://127.0.0.1:3306/account_db
    username: root
    password: 1234
    # password: "{cipher}4b26e49a9df146d379e3cdf9a19296bcecc2f8fafc80a35fade7c7e605ee039c"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update  # none (실제 운영), update
    show-sql: true      # 실행되는 SQL문을 화면에 출력
    properties:         
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


 
# Eureka Server에 자가 등록
eureka:
  instance:
    prefer-ip-address: true   # Eureka 클라이언트가 자신을 등록할 때, 호스트 이름 대신 IP 주소를 사용하여 서비스 레지스리에 등록한다. 
  client:  
    register-with-eureka: true   
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/        
      # defaultZone: ${UREKA_CLIENT_SERVICE_URL}  # http://localhost:8761/eureka/
                